# Generated by Django 5.2.9 on 2026-01-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='13 Digit ISBN', max_length=13),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Priced', 'Priced - Waiting User Approval'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
